[tool.black]
line-length = 120

[tool.isort]
combine_as_imports=true
line_length = 120
profile = "black"

[tool.ruff]
line-length = 120

[flake8]
max-line-length = 120
exclude = ".git,__pycache__,docs/source/conf.py,old,build,dist"
